# Generated by Django 5.0.2 on 2024-03-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product/images/')),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
