# Generated by Django 5.0.2 on 2024-03-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='type.type'),
        ),
    ]
